import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Provider from "@/providers/provider";

export const metadata: Metadata = {
  title: "task management app",
  description: "Generated by create next app",
};

const myFont = localFont({
  src: "../../public/fonts/IRANSans-web.woff",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className={myFont.className}>
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
