import type {Metadata} from "next";
import "./globals.css";
import StyledComponentsRegistry from "@/lib/registry";
import {Screen} from "@/lib/globalStyles";
import localFont from "next/font/local";

export const metadata: Metadata = {
    title: "task management app",
    description: "Generated by create next app",
};


const myFont = localFont({
    src: '../../public/fonts/IRANSans-web.woff'
})
export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fa" className={myFont.className}>
        <body>
        <StyledComponentsRegistry>
            <Screen>{children}</Screen>
        </StyledComponentsRegistry>
        </body>
        </html>
    );
}
